In [774]:
import numpy as np
import pandas as pd
import warnings
warnings.filterwarnings("ignore")
pd.set_option("display.max_columns", 50)

In [775]:
df = pd.read_csv("Employee _AND_Salary.csv")

In [776]:
df.shape

(15045, 33)

In [777]:
df.head()

,Employee_ID,First_Name,Last_Name,Full_Name,Email,Phone,Gender,Age,Department,Job_Title,Grade_Level,Manager_ID,Office_City,State,Country,Education_Level,Employment_Type,Work_Mode,Date_of_Joining,Years_Experience,Base_Salary_INR,Annual_Bonus_INR,Monthly_Allowance_INR,Annual_Deductions_INR,Gross_Annual_Pay_INR,Net_Annual_Pay_INR,Salary_Band,Performance_Rating,Employment_Status,Last_Promotion_Date,Marital_Status,Overtime_Hours_Monthly,Training_Hours_Yearly
0,EMP100001,Tanvi,Gupta,Tanvi Gupta,tanvi.gupta0@example.com,+91-9938391112,Female,37.0,Legal,Legal Counsel,L6,EMP103528,Kolkata,West Bengal,India,Diploma,Contract,on-site,2015-02-22,17.1,1194785,202981,5812.25,86781,1467513,1380732,B1,Needs Improvement,Active,2016-07-16,Married,15,33
1,EMP100002,Reyansh,Joshi,Reyansh Joshi,reyansh.joshi1@example.com,+91-6592116294,Female,27.0,Legal,Compliance Analyst,L2,EMP102685,Bengaluru,Karnataka,India,Diploma,Full-time,Remote,2014-12-26,18.3,292724,40638,2616.92,23172,364765,341593,B6,Meets Expectations,Active,2020-01-12,Divorced,0,30
2,EMP100003,Sneha,Das,Sneha Das,sneha.das2@example.com,+91-6448787558,Prefer not to say,31.0,Operations,Team Lead,L4,EMP112072,Noida,Uttar Pradesh,India,Master's,Intern,Hybrid,2024-05-06,4.9,352053,22195,2191.17,35236,400542,365306,B2,Outstanding,Active,2025-07-10,Divorced,4,23
3,EMP100004,Aarav,Shah,Aarav Shah,aarav.shah3@example.com,+91-7810498338,Prefer not to say,22.0,Customer Support,Support Specialist,L6,EMP109627,Mumbai,Maharashtra,India,High School,Full-time,Remote,2016-11-28,10.3,1125744,134182,2435.08,138249,1289147,1150898,B4,Meets Expectations,Active,2026-02-06,Married,5,46
4,EMP100005,Vivaan,Das,Vivaan Das,vivaan.das4@example.com,+91-9845890592,Male,40.0,engineering,QA Engineer,L1,EMP104242,Bengaluru,Karnataka,India,Master's,Intern,Hybrid,2022-12-26,4.4,1330323,148012,7969.17,88114,1573965,1485851,B6,Meets Expectations,Resigned,NaN,Single,23,26

In [778]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 15045 entries, 0 to 15044
Data columns (total 33 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Employee_ID             15045 non-null  str
 1   First_Name              15045 non-null  str
 2   Last_Name               15045 non-null  str
 3   Full_Name               15045 non-null  str
 4   Email                   14652 non-null  str
 5   Phone                   14520 non-null  str
 6   Gender                  15045 non-null  str
 7   Age                     14882 non-null  float64
 8   Department              15045 non-null  str
 9   Job_Title               15045 non-null  str
 10  Grade_Level             15045 non-null  str
 11  Manager_ID              14436 non-null  str
 12  Office_City             15045 non-null  str
 13  State                   15045 non-null  str
 14  Country                 15045 non-null  str
 15  Education_Level         14691 non-null  str
 16  Employment_Type         15045 non-null  str
 17  Work_Mode               15045 non-null  str
 18  Date_of_Joining         15045 non-null  str
 19  Years_Experience        15045 non-null  str
 20  Base_Salary_INR         15045 non-null  str
 21  Annual_Bonus_INR        15045 non-null  str
 22  Monthly_Allowance_INR   14729 non-null  float64
 23  Annual_Deductions_INR   15045 non-null  int64
 24  Gross_Annual_Pay_INR    15045 non-null  int64
 25  Net_Annual_Pay_INR      15045 non-null  int64
 26  Salary_Band             15045 non-null  str
 27  Performance_Rating      14781 non-null  str
 28  Employment_Status       15045 non-null  str
 29  Last_Promotion_Date     12709 non-null  str
 30  Marital_Status          15045 non-null  str
 31  Overtime_Hours_Monthly  15045 non-null  int64
 32  Training_Hours_Yearly   15045 non-null  int64
dtypes: float64(2), int64(5), str(26)
memory usage: 3.8 MB

In [779]:
df.dtypes

Employee_ID                   str
First_Name                    str
Last_Name                     str
Full_Name                     str
Email                         str
Phone                         str
Gender                        str
Age                       float64
Department                    str
Job_Title                     str
Grade_Level                   str
Manager_ID                    str
Office_City                   str
State                         str
Country                       str
Education_Level               str
Employment_Type               str
Work_Mode                     str
Date_of_Joining               str
Years_Experience              str
Base_Salary_INR               str
Annual_Bonus_INR              str
Monthly_Allowance_INR     float64
Annual_Deductions_INR       int64
Gross_Annual_Pay_INR        int64
Net_Annual_Pay_INR          int64
Salary_Band                   str
Performance_Rating            str
Employment_Status             str
Last_Promotion_Date           str
Marital_Status                str
Overtime_Hours_Monthly      int64
Training_Hours_Yearly       int64
dtype: object

In [780]:
df.describe()

,Age,Monthly_Allowance_INR,Annual_Deductions_INR,Gross_Annual_Pay_INR,Net_Annual_Pay_INR,Overtime_Hours_Monthly,Training_Hours_Yearly
count,14882.000000,14729.000000,15045.000000,1.504500e+04,1.504500e+04,15045.000000,15045.000000
mean,32.947588,5044.007119,86074.712795,1.015458e+06,9.291061e+05,7.966899,23.512861
std,8.211599,3272.459704,52357.462523,4.742750e+05,4.357397e+05,6.158489,11.581678
min,-5.000000,300.250000,-184708.000000,1.842050e+05,1.606620e+05,0.000000,0.000000
25%,27.000000,2454.670000,46095.000000,6.714060e+05,6.120900e+05,3.000000,16.000000
50%,33.000000,4374.580000,76765.000000,1.005370e+06,9.181940e+05,7.000000,24.000000
75%,38.000000,6994.830000,117506.000000,1.335307e+06,1.222228e+06,12.000000,31.000000
max,150.000000,20970.580000,335835.000000,2.819459e+06,2.658552e+06,31.000000,71.000000

In [781]:
df.columns

Index(['Employee_ID', 'First_Name', 'Last_Name', 'Full_Name', 'Email', 'Phone',
       'Gender', 'Age', 'Department', 'Job_Title', 'Grade_Level', 'Manager_ID',
       'Office_City', 'State', 'Country', 'Education_Level', 'Employment_Type',
       'Work_Mode', 'Date_of_Joining', 'Years_Experience', 'Base_Salary_INR',
       'Annual_Bonus_INR', 'Monthly_Allowance_INR', 'Annual_Deductions_INR',
       'Gross_Annual_Pay_INR', 'Net_Annual_Pay_INR', 'Salary_Band',
       'Performance_Rating', 'Employment_Status', 'Last_Promotion_Date',
       'Marital_Status', 'Overtime_Hours_Monthly', 'Training_Hours_Yearly'],
      dtype='str')

In [782]:
df.columns = df.columns.str.strip().str.replace(" ","_")

In [783]:
df.columns

Index(['Employee_ID', 'First_Name', 'Last_Name', 'Full_Name', 'Email', 'Phone',
       'Gender', 'Age', 'Department', 'Job_Title', 'Grade_Level', 'Manager_ID',
       'Office_City', 'State', 'Country', 'Education_Level', 'Employment_Type',
       'Work_Mode', 'Date_of_Joining', 'Years_Experience', 'Base_Salary_INR',
       'Annual_Bonus_INR', 'Monthly_Allowance_INR', 'Annual_Deductions_INR',
       'Gross_Annual_Pay_INR', 'Net_Annual_Pay_INR', 'Salary_Band',
       'Performance_Rating', 'Employment_Status', 'Last_Promotion_Date',
       'Marital_Status', 'Overtime_Hours_Monthly', 'Training_Hours_Yearly'],
      dtype='str')

In [784]:
df.duplicated().sum()

np.int64(45)

In [785]:
df = df.drop_duplicates()

In [786]:
df.duplicated().sum()

np.int64(0)

In [787]:
df.isna().sum()

Employee_ID                  0
First_Name                   0
Last_Name                    0
Full_Name                    0
Email                      392
Phone                      523
Gender                       0
Age                        163
Department                   0
Job_Title                    0
Grade_Level                  0
Manager_ID                 607
Office_City                  0
State                        0
Country                      0
Education_Level            354
Employment_Type              0
Work_Mode                    0
Date_of_Joining              0
Years_Experience             0
Base_Salary_INR              0
Annual_Bonus_INR             0
Monthly_Allowance_INR      316
Annual_Deductions_INR        0
Gross_Annual_Pay_INR         0
Net_Annual_Pay_INR           0
Salary_Band                  0
Performance_Rating         263
Employment_Status            0
Last_Promotion_Date       2332
Marital_Status               0
Overtime_Hours_Monthly       0
Training_Hours_Yearly        0
dtype: int64

In [788]:
df.isna().sum().sum()

np.int64(4950)

In [789]:
df["Email"].isna().sum()

np.int64(392)

In [790]:
df["Email"] = df["Email"].fillna("Unknown")

In [791]:
df["Email"].isna().sum()

np.int64(0)

In [792]:
df["Phone"] = df["Phone"].fillna("Not Available")

In [793]:
df["Phone"].isna().sum()

np.int64(0)

In [794]:
df["Manager_ID"].head()

0    EMP103528
1    EMP102685
2    EMP112072
3    EMP109627
4    EMP104242
Name: Manager_ID, dtype: str

In [795]:
print(df["Manager_ID"].dtype)

str

In [796]:
df["Manager_ID"].isna().sum()

np.int64(607)

In [797]:
df["Manager_ID"] = df["Manager_ID"].fillna("Unknown")

In [798]:
df["Manager_ID"].isna().sum()

np.int64(0)

In [799]:
df["Employee_ID"].head()

0    EMP100001
1    EMP100002
2    EMP100003
3    EMP100004
4    EMP100005
Name: Employee_ID, dtype: str

In [800]:
df["Employee_ID"].isna().sum()

np.int64(0)

In [801]:
df["Employee_ID"].duplicated().sum()

np.int64(0)

In [802]:
print(df["Employee_ID"].dtype)

str

In [803]:
df["Employee_ID"] = df["Employee_ID"].str.strip()

In [804]:
print("Duplicate rows:", df.duplicated().sum())

Duplicate rows: 0

In [805]:
df["Education_Level"].head()

0        Diploma
1        Diploma
2       Master's
3    High School
4       Master's
Name: Education_Level, dtype: str

In [806]:
df["Education_Level"].isna().sum()

np.int64(354)

In [807]:
df["Education_Level"] = df["Education_Level"].fillna("Unknown")

In [808]:
df["Education_Level"].isna().sum()

np.int64(0)

In [809]:
df["Performance_Rating"].head()

0     Needs Improvement
1    Meets Expectations
2           Outstanding
3    Meets Expectations
4    Meets Expectations
Name: Performance_Rating, dtype: str

In [810]:
df["Performance_Rating"].isna().sum()

np.int64(263)

In [811]:
df["Performance_Rating"] = df["Performance_Rating"].fillna("Unknown")

In [812]:
df["Performance_Rating"].isna().sum()

np.int64(0)

In [813]:
df["Monthly_Allowance_INR"].head()

0    5812.25
1    2616.92
2    2191.17
3    2435.08
4    7969.17
Name: Monthly_Allowance_INR, dtype: float64

In [814]:
df["Monthly_Allowance_INR"] = df["Monthly_Allowance_INR"].fillna(df["Monthly_Allowance_INR"].median())

In [815]:
df["Monthly_Allowance_INR"].isna().sum()

np.int64(0)

In [816]:
df["Age"].dtype

dtype('float64')

In [817]:
df["Age"].min()

np.float64(-5.0)

In [818]:
df.loc[~df["Age"].between(18, 65), "Age"] = np.nan

In [819]:
df["Age"].isna().sum()

np.int64(183)

In [820]:
df["Age"] = df["Age"].fillna(df["Age"].median())

df["Age"].isna().sum()

np.int64(0)

In [821]:
df["Age"].min()

np.float64(21.0)

In [822]:
df["Annual_Bonus_INR"].head()

0    202981
1     40638
2     22195
3    134182
4    148012
Name: Annual_Bonus_INR, dtype: str

In [823]:
df["Annual_Bonus_INR"].dtype

In [824]:
df["Annual_Deductions_INR"].min()

np.int64(-184708)

In [825]:
df.loc[df["Annual_Deductions_INR"] < 0, "Annual_Deductions_INR"] = 0

In [826]:
df["Annual_Deductions_INR"].min()

np.int64(0)

In [827]:
df[["Years_Experience", "Base_Salary_INR","Annual_Bonus_INR" ]].head()

  Years_Experience Base_Salary_INR Annual_Bonus_INR
0             17.1         1194785           202981
1             18.3          292724            40638
2              4.9          352053            22195
3             10.3         1125744           134182
4              4.4         1330323           148012

In [828]:
df[["Years_Experience", "Base_Salary_INR","Annual_Bonus_INR" ]].dtypes

Years_Experience    str
Base_Salary_INR     str
Annual_Bonus_INR    str
dtype: object

In [829]:
df["Years_Experience"] = pd.to_numeric(df["Years_Experience"],errors="coerce")

In [830]:
df["Base_Salary_INR"] = pd.to_numeric(df[ "Base_Salary_INR"],errors="coerce")

In [831]:
df["Annual_Bonus_INR"] = pd.to_numeric(df["Annual_Bonus_INR"],errors="coerce")

In [832]:
df[["Years_Experience", "Base_Salary_INR","Annual_Bonus_INR" ]].isna().sum()

Years_Experience     13
Base_Salary_INR     214
Annual_Bonus_INR    119
dtype: int64

In [833]:
df.loc[df["Years_Experience"] < 0,"Years_Experience"] = np.nan

In [834]:
numeric_cols = [
    "Years_Experience",
    "Base_Salary_INR",
    "Annual_Bonus_INR"
]

for col in numeric_cols:
    df[col] = pd.to_numeric(
        df[col], errors="coerce"
    )

In [835]:
df["Years_Experience"] = df["Years_Experience"].fillna(df["Years_Experience"].median())

In [836]:
df["Years_Experience"].isna().sum()

np.int64(0)

In [837]:
df[["Base_Salary_INR","Annual_Bonus_INR" ]] = df[
    ["Base_Salary_INR",
     "Annual_Bonus_INR" ]].fillna(df[["Base_Salary_INR","Annual_Bonus_INR" ]].median())

In [838]:
df[["Base_Salary_INR","Annual_Bonus_INR" ]].isna().sum()

Base_Salary_INR     0
Annual_Bonus_INR    0
dtype: int64

In [839]:
df["Date_of_Joining"].head()

0    2015-02-22
1    2014-12-26
2    2024-05-06
3    2016-11-28
4    2022-12-26
Name: Date_of_Joining, dtype: str

In [840]:
df["Date_of_Joining"] = pd.to_datetime(df["Date_of_Joining"],errors="coerce")

In [841]:
df[df["Date_of_Joining"].isna()]

,Employee_ID,First_Name,Last_Name,Full_Name,Email,Phone,Gender,Age,Department,Job_Title,Grade_Level,Manager_ID,Office_City,State,Country,Education_Level,Employment_Type,Work_Mode,Date_of_Joining,Years_Experience,Base_Salary_INR,Annual_Bonus_INR,Monthly_Allowance_INR,Annual_Deductions_INR,Gross_Annual_Pay_INR,Net_Annual_Pay_INR,Salary_Band,Performance_Rating,Employment_Status,Last_Promotion_Date,Marital_Status,Overtime_Hours_Monthly,Training_Hours_Yearly
34,EMP100035,Rahul,Sharma,Rahul Sharma,rahul.sharma34@example.com,+91-8256729208,Female,36.0,Human Resources,People Analyst,L1,EMP102371,Noida,Uttar Pradesh,India,Master's,Full-time,Remote,NaT,7.6,1184694.0,132884.0,10113.92,112069,1438945,1326876,B3,Meets Expectations,Active,2021-03-19,Divorced,8,24
60,EMP100061,Reyansh,Mehta,Reyansh Mehta,reyansh.mehta60@example.com,+91-7541022035,Non-binary,24.0,Human Resources,People Analyst,L3,EMP107369,Surat,Gujarat,India,High School,Full-time,On-site,NaT,10.6,1298608.0,132090.0,9535.25,144857,1545121,1400264,B2,Meets Expectations,Active,2026-08-11,Single,7,28
79,EMP100080,Nikhil,Choudhary,Nikhil Choudhary,nikhil.choudhary79@example.com,+91-9991385965,Non-binary,36.0,Human Resources,HR Executive,L1,EMP112075,Gurugram,Haryana,India,PhD,Contract,Hybrid,NaT,11.0,800130.0,19992.0,4752.42,126805,877151,750346,B1,Needs Improvement,Active,2026-07-21,Divorced,0,18
85,EMP100086,Priya,Desai,Priya Desai,priya.desai85@example.com,+91-9815172133,Prefer not to say,40.0,IT,System Administrator,L5,EMP111319,Kolkata,West Bengal,India,PhD,Full-time,Hybrid,NaT,3.7,563988.0,10523.0,3893.00,56793,621227,564434,B3,Meets Expectations,Active,NaN,Divorced,3,36
103,EMP100104,Kiran,Singh,Kiran Singh,kiran.singh6@example.com,+91-8259072938,Female,26.0,IT,IT Manager,L2,EMP102000,Bengaluru,Karnataka,India,Bachelor's,Full-time,Hybrid,NaT,16.9,583778.0,124980.0,2208.67,38322,735262,696940,B5,Exceeds Expectations,Active,NaN,Divorced,8,43
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14850,EMP114851,Tanvi,Yadav,Tanvi Yadav,tanvi.yadav9@example.com,+91-6725351961,Male,41.0,Customer Support,Support Specialist,L6,EMP103355,Noida,Uttar Pradesh,India,Master's,Full-time,Hybrid,NaT,4.3,1303750.0,140229.0,6184.67,56542,1518195,1461653,B5,Unknown,On Leave,NaN,Single,8,20
14907,EMP114908,Nikhil,Shah,Nikhil Shah,nikhil.shah66@example.com,+91-7926326114,Female,41.0,Operations,Team Lead,L3,EMP108472,Noida,Uttar Pradesh,India,Master's,Full-time,Hybrid,NaT,15.6,539487.0,112040.0,1666.75,59046,671528,612482,B6,Meets Expectations,Active,2017-08-15,Single,9,22
14948,EMP114949,Neha,Choudhary,Neha Choudhary,neha.choudhary10@example.com,+91-8450882420,Prefer not to say,31.0,Customer Support,Support Specialist,L5,EMP105726,Kolkata,West Bengal,India,Master's,Full-time,Remote,NaT,11.1,234288.0,20412.0,510.25,11534,260823,249289,B4,Exceeds Expectations,Resigned,2022-05-28,Married,11,39
14959,EMP114960,Vivaan,Mishra,Vivaan Mishra,vivaan.mishra21@example.com,+91-8047069995,Male,44.0,Legal,Compliance Analyst,L6,EMP109862,Gurugram,Haryana,India,Diploma,Full-time,Remote,NaT,15.4,1249643.0,12188.0,4435.25,90987,1315054,1224067,B1,Meets Expectations,Active,2018-12-19,Married,24,38
14983,EMP114984,Ishaan,Joshi,Ishaan Joshi,ishaan.joshi45@example.com,+91-9983972761,Non-binary,36.0,Operations,Operations Analyst,L6,EMP106891,Kolkata,West Bengal,India,Diploma,Full-time,HYBRID,NaT,10.9,1005078.0,146187.0,3224.08,100160,1189954,1089794,B6,Exceeds Expectations,Resigned,2025-07-26,Single,16,2

In [842]:
df["Date_of_Joining"].isna().sum()

np.int64(500)

In [843]:
df["Date_of_Joining"]=  df["Date_of_Joining"].fillna(df["Date_of_Joining"].mode()[0])

In [844]:
print(df["Date_of_Joining"].dtype)

datetime64[us]

In [845]:

df["Date_of_Joining"].isna().sum()

np.int64(0)

In [846]:
df["Last_Promotion_Date"].head()

0    2016-07-16
1    2020-01-12
2    2025-07-10
3    2026-02-06
4           NaN
Name: Last_Promotion_Date, dtype: str

In [847]:
df["Last_Promotion_Date"] = pd.to_datetime(df["Last_Promotion_Date"],errors= "coerce")

In [848]:
df["Last_Promotion_Date"].isna().sum()

np.int64(2332)

In [849]:
df[df["Last_Promotion_Date"].isna()]

,Employee_ID,First_Name,Last_Name,Full_Name,Email,Phone,Gender,Age,Department,Job_Title,Grade_Level,Manager_ID,Office_City,State,Country,Education_Level,Employment_Type,Work_Mode,Date_of_Joining,Years_Experience,Base_Salary_INR,Annual_Bonus_INR,Monthly_Allowance_INR,Annual_Deductions_INR,Gross_Annual_Pay_INR,Net_Annual_Pay_INR,Salary_Band,Performance_Rating,Employment_Status,Last_Promotion_Date,Marital_Status,Overtime_Hours_Monthly,Training_Hours_Yearly
4,EMP100005,Vivaan,Das,Vivaan Das,vivaan.das4@example.com,+91-9845890592,Male,40.0,engineering,QA Engineer,L1,EMP104242,Bengaluru,Karnataka,India,Master's,Intern,Hybrid,2022-12-26,4.4,1330323.0,148012.0,7969.17,88114,1573965,1485851,B6,Meets Expectations,Resigned,NaT,Single,23,26
13,EMP100014,Ananya,Nair,Ananya Nair,ananya.nair13@example.com,+91-9517706419,Prefer not to say,36.0,Human Resources,Recruiter,L5,EMP108427,Indore,Madhya Pradesh,India,Bachelor's,Full-time,Hybrid,2016-08-04,15.4,645791.0,127365.0,2859.67,35740,807472,771732,B1,Meets Expectations,Active,NaT,Prefer not to say,10,25
17,EMP100018,Ananya,Verma,Ananya Verma,ananya.verma17@example.com,+91-9591006351,Non-binary,32.0,Finance,Finance Manager,L4,EMP100312,Kolkata,West Bengal,India,PhD,Full-time,On-site,2022-10-31,11.8,327537.0,67437.0,1767.75,18049,416187,398138,B6,Meets Expectations,Active,NaT,Prefer not to say,1,24
18,EMP100019,Rahul,Kulkarni,Rahul Kulkarni,rahul.kulkarni18@example.com,+91-9826501977,Prefer not to say,40.0,Engineering,Engineering Manager,L2,EMP108931,Hyderabad,Telangana,India,PhD,Contract,Hybrid,2026-01-31,3.8,280720.0,61187.0,643.00,42022,349623,307601,B6,Exceeds Expectations,Active,NaT,Prefer not to say,12,17
20,EMP100021,Akash,Patel,Akash Patel,akash.patel20@example.com,+91-8170165072,Non-binary,40.0,ENGINEERING,Engineering Manager,L5,EMP101744,Ahmedabad,Gujarat,India,Bachelor's,Full-time,Remote,2014-04-05,13.1,1444926.0,163092.0,13299.17,161620,1767608,1605988,B5,Exceeds Expectations,Active,NaT,Prefer not to say,10,21
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14961,EMP114962,Krishna,Kulkarni,Krishna Kulkarni,krishna.kulkarni23@example.com,+91-6907856467,Male,24.0,IT,Network Engineer,L1,EMP107504,Chennai,Tamil Nadu,India,Unknown,Full-time,Remote,2015-09-04,13.0,993769.0,195521.0,2514.33,143960,1219462,1075502,B1,Meets Expectations,Active,NaT,Single,10,34
14965,EMP114966,Jaya,Joshi,Jaya Joshi,jaya.joshi27@example.com,+91-8410946569,Non-binary,31.0,Engineering,Senior Software Engineer,L3,EMP105392,Bengaluru,Karnataka,India,High School,Full-time,On-site,2024-08-30,4.1,987881.0,164908.0,5111.17,51454,1214123,1162669,B1,Meets Expectations,Resigned,NaT,Prefer not to say,0,39
14975,EMP114976,Vihaan,Patel,Vihaan Patel,vihaan.patel37@example.com,+91-8675426047,Non-binary,37.0,Customer Support,Support Associate,L5,EMP101987,Gurugram,Haryana,India,Diploma,Contract,Hybrid,2022-10-27,10.3,180000.0,20566.0,1412.67,11544,217518,205974,B2,Needs Improvement,Active,NaT,Married,0,38
14991,EMP114992,Kavya,Saxena,Kavya Saxena,kavya.saxena53@example.com,+91-6891264910,Non-binary,25.0,Data Science,Data Analyst,L5,EMP101154,Indore,Madhya Pradesh,India,Bachelor's,Full-time,On-site,2026-05-05,6.7,1212021.0,96906.0,2344.25,81973,1337058,1255085,B5,Exceeds Expectations,Active,NaT,Single,11,19
14994,EMP114995,Vivaan,Verma,Vivaan Verma,vivaan.verma56@example.com,+91-8716848736,Prefer not to say,24.0,Sales,Sales Manager,L2,EMP100459,Kolkata,West Bengal,India,High School,Full-time,Hybrid,2014-05-07,18.8,1006421.0,208420.0,9560.25,140181,1329564,1189383,B3,Meets Expectations,Active,NaT,Married,4,8

In [850]:
df["Last_Promotion_Date"] = df["Last_Promotion_Date"].fillna(df["Last_Promotion_Date"].mode()[0])

In [851]:
df["Last_Promotion_Date"].isna().sum()

np.int64(0)

In [852]:
print(df["Last_Promotion_Date"].dtype)

datetime64[us]

In [853]:
df["Department"].unique()

<StringArray>
[           'Legal',       'Operations', 'Customer Support',
    ' engineering ',        'Marketing',     'Data Science',
            'Sales',      'Engineering',               'IT',
  'Human Resources',          'Finance',      'ENGINEERING',
      ' marketing ',        'MARKETING',    'Engineering  ',
           ' sales',          'Sales  ',           'SALES ']
Length: 18, dtype: str

In [854]:
df["Department"] = df["Department"].str.strip().str.title().str.replace(" ","_")

In [855]:
df["Department"].value_counts(dropna= False)

Department
Marketing           1547
Operations          1517
Legal               1513
Engineering         1502
Finance             1495
Customer_Support    1494
Sales               1494
Human_Resources     1482
Data_Science        1479
It                  1477
Name: count, dtype: int64

In [856]:
df["Department"].unique()

<StringArray>
[           'Legal',       'Operations', 'Customer_Support',
      'Engineering',        'Marketing',     'Data_Science',
            'Sales',               'It',  'Human_Resources',
          'Finance']
Length: 10, dtype: str

In [857]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 15000 entries, 0 to 14999
Data columns (total 33 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Employee_ID             15000 non-null  str
 1   First_Name              15000 non-null  str
 2   Last_Name               15000 non-null  str
 3   Full_Name               15000 non-null  str
 4   Email                   15000 non-null  str
 5   Phone                   15000 non-null  str
 6   Gender                  15000 non-null  str
 7   Age                     15000 non-null  float64
 8   Department              15000 non-null  str
 9   Job_Title               15000 non-null  str
 10  Grade_Level             15000 non-null  str
 11  Manager_ID              15000 non-null  str
 12  Office_City             15000 non-null  str
 13  State                   15000 non-null  str
 14  Country                 15000 non-null  str
 15  Education_Level         15000 non-null  str
 16  Employment_Type         15000 non-null  str
 17  Work_Mode               15000 non-null  str
 18  Date_of_Joining         15000 non-null  datetime64[us]
 19  Years_Experience        15000 non-null  float64
 20  Base_Salary_INR         15000 non-null  float64
 21  Annual_Bonus_INR        15000 non-null  float64
 22  Monthly_Allowance_INR   15000 non-null  float64
 23  Annual_Deductions_INR   15000 non-null  int64
 24  Gross_Annual_Pay_INR    15000 non-null  int64
 25  Net_Annual_Pay_INR      15000 non-null  int64
 26  Salary_Band             15000 non-null  str
 27  Performance_Rating      15000 non-null  str
 28  Employment_Status       15000 non-null  str
 29  Last_Promotion_Date     15000 non-null  datetime64[us]
 30  Marital_Status          15000 non-null  str
 31  Overtime_Hours_Monthly  15000 non-null  int64
 32  Training_Hours_Yearly   15000 non-null  int64
dtypes: datetime64[us](2), float64(5), int64(5), str(21)
memory usage: 3.8 MB

In [858]:
df.isna().sum()

Employee_ID               0
First_Name                0
Last_Name                 0
Full_Name                 0
Email                     0
Phone                     0
Gender                    0
Age                       0
Department                0
Job_Title                 0
Grade_Level               0
Manager_ID                0
Office_City               0
State                     0
Country                   0
Education_Level           0
Employment_Type           0
Work_Mode                 0
Date_of_Joining           0
Years_Experience          0
Base_Salary_INR           0
Annual_Bonus_INR          0
Monthly_Allowance_INR     0
Annual_Deductions_INR     0
Gross_Annual_Pay_INR      0
Net_Annual_Pay_INR        0
Salary_Band               0
Performance_Rating        0
Employment_Status         0
Last_Promotion_Date       0
Marital_Status            0
Overtime_Hours_Monthly    0
Training_Hours_Yearly     0
dtype: int64

In [859]:
df.isna().sum().sum()

np.int64(0)

In [860]:
df.duplicated().sum()

np.int64(0)

In [861]:
df.describe()

,Age,Date_of_Joining,Years_Experience,Base_Salary_INR,Annual_Bonus_INR,Monthly_Allowance_INR,Annual_Deductions_INR,Gross_Annual_Pay_INR,Net_Annual_Pay_INR,Last_Promotion_Date,Overtime_Hours_Monthly,Training_Hours_Yearly
count,15000.000000,15000,15000.000000,1.500000e+04,15000.000000,15000.000000,15000.000000,1.500000e+04,1.500000e+04,15000,15000.000000,15000.000000
mean,32.896200,2020-04-07 14:34:56.640000,10.369627,8.599239e+05,94729.102133,5029.282692,86228.278733,1.015417e+06,9.290498e+05,2023-12-08 07:13:09.120000,7.968000,23.521400
min,21.000000,2014-01-01 00:00:00,0.100000,1.800000e+05,0.000000,300.250000,0.000000,1.842050e+05,1.606620e+05,2014-08-31 00:00:00,0.000000,0.000000
25%,27.000000,2017-04-24 18:00:00,7.200000,5.757158e+05,34637.000000,2500.687500,46101.000000,6.714435e+05,6.122205e+05,2022-05-29 00:00:00,3.000000,16.000000
50%,33.000000,2020-02-27 00:00:00,10.400000,8.533770e+05,77895.000000,4373.455000,76765.500000,1.004886e+06,9.179395e+05,2024-11-25 00:00:00,7.000000,24.000000
75%,38.000000,2023-05-27 00:00:00,13.500000,1.124672e+06,138460.500000,6930.042500,117505.250000,1.335206e+06,1.222124e+06,2026-03-05 00:00:00,12.000000,31.000000
max,62.000000,2026-09-30 00:00:00,20.700000,2.459790e+06,460273.000000,20970.580000,335835.000000,2.819459e+06,2.658552e+06,2026-09-30 00:00:00,31.000000,71.000000
std,7.527762,NaN,4.307403,3.944304e+05,74161.211786,3237.952887,51975.055065,4.741665e+05,4.355951e+05,NaN,6.158704,11.581875

In [862]:
print(df.dtypes.all)

<bound method Series.all of Employee_ID                          str
First_Name                           str
Last_Name                            str
Full_Name                            str
Email                                str
Phone                                str
Gender                               str
Age                              float64
Department                           str
Job_Title                            str
Grade_Level                          str
Manager_ID                           str
Office_City                          str
State                                str
Country                              str
Education_Level                      str
Employment_Type                      str
Work_Mode                            str
Date_of_Joining           datetime64[us]
Years_Experience                 float64
Base_Salary_INR                  float64
Annual_Bonus_INR                 float64
Monthly_Allowance_INR            float64
Annual_Deductions_INR              int64
Gross_Annual_Pay_INR               int64
Net_Annual_Pay_INR                 int64
Salary_Band                          str
Performance_Rating                   str
Employment_Status                    str
Last_Promotion_Date       datetime64[us]
Marital_Status                       str
Overtime_Hours_Monthly             int64
Training_Hours_Yearly              int64
dtype: object>

In [863]:
df.select_dtypes(include="object").head()

,Employee_ID,First_Name,Last_Name,Full_Name,Email,Phone,Gender,Department,Job_Title,Grade_Level,Manager_ID,Office_City,State,Country,Education_Level,Employment_Type,Work_Mode,Salary_Band,Performance_Rating,Employment_Status,Marital_Status
0,EMP100001,Tanvi,Gupta,Tanvi Gupta,tanvi.gupta0@example.com,+91-9938391112,Female,Legal,Legal Counsel,L6,EMP103528,Kolkata,West Bengal,India,Diploma,Contract,on-site,B1,Needs Improvement,Active,Married
1,EMP100002,Reyansh,Joshi,Reyansh Joshi,reyansh.joshi1@example.com,+91-6592116294,Female,Legal,Compliance Analyst,L2,EMP102685,Bengaluru,Karnataka,India,Diploma,Full-time,Remote,B6,Meets Expectations,Active,Divorced
2,EMP100003,Sneha,Das,Sneha Das,sneha.das2@example.com,+91-6448787558,Prefer not to say,Operations,Team Lead,L4,EMP112072,Noida,Uttar Pradesh,India,Master's,Intern,Hybrid,B2,Outstanding,Active,Divorced
3,EMP100004,Aarav,Shah,Aarav Shah,aarav.shah3@example.com,+91-7810498338,Prefer not to say,Customer_Support,Support Specialist,L6,EMP109627,Mumbai,Maharashtra,India,High School,Full-time,Remote,B4,Meets Expectations,Active,Married
4,EMP100005,Vivaan,Das,Vivaan Das,vivaan.das4@example.com,+91-9845890592,Male,Engineering,QA Engineer,L1,EMP104242,Bengaluru,Karnataka,India,Master's,Intern,Hybrid,B6,Meets Expectations,Resigned,Single

In [864]:
df.shape

(15000, 33)

In [865]:
df.isna().sum()

Employee_ID               0
First_Name                0
Last_Name                 0
Full_Name                 0
Email                     0
Phone                     0
Gender                    0
Age                       0
Department                0
Job_Title                 0
Grade_Level               0
Manager_ID                0
Office_City               0
State                     0
Country                   0
Education_Level           0
Employment_Type           0
Work_Mode                 0
Date_of_Joining           0
Years_Experience          0
Base_Salary_INR           0
Annual_Bonus_INR          0
Monthly_Allowance_INR     0
Annual_Deductions_INR     0
Gross_Annual_Pay_INR      0
Net_Annual_Pay_INR        0
Salary_Band               0
Performance_Rating        0
Employment_Status         0
Last_Promotion_Date       0
Marital_Status            0
Overtime_Hours_Monthly    0
Training_Hours_Yearly     0
dtype: int64

In [866]:
print(df.isna().sum().sum())

0

In [867]:
df.duplicated().sum()

np.int64(0)

In [868]:
print(df.dtypes)

Employee_ID                          str
First_Name                           str
Last_Name                            str
Full_Name                            str
Email                                str
Phone                                str
Gender                               str
Age                              float64
Department                           str
Job_Title                            str
Grade_Level                          str
Manager_ID                           str
Office_City                          str
State                                str
Country                              str
Education_Level                      str
Employment_Type                      str
Work_Mode                            str
Date_of_Joining           datetime64[us]
Years_Experience                 float64
Base_Salary_INR                  float64
Annual_Bonus_INR                 float64
Monthly_Allowance_INR            float64
Annual_Deductions_INR              int64
Gross_Annual_Pay_INR               int64
Net_Annual_Pay_INR                 int64
Salary_Band                          str
Performance_Rating                   str
Employment_Status                    str
Last_Promotion_Date       datetime64[us]
Marital_Status                       str
Overtime_Hours_Monthly             int64
Training_Hours_Yearly              int64
dtype: object

In [869]:
df.describe()

,Age,Date_of_Joining,Years_Experience,Base_Salary_INR,Annual_Bonus_INR,Monthly_Allowance_INR,Annual_Deductions_INR,Gross_Annual_Pay_INR,Net_Annual_Pay_INR,Last_Promotion_Date,Overtime_Hours_Monthly,Training_Hours_Yearly
count,15000.000000,15000,15000.000000,1.500000e+04,15000.000000,15000.000000,15000.000000,1.500000e+04,1.500000e+04,15000,15000.000000,15000.000000
mean,32.896200,2020-04-07 14:34:56.640000,10.369627,8.599239e+05,94729.102133,5029.282692,86228.278733,1.015417e+06,9.290498e+05,2023-12-08 07:13:09.120000,7.968000,23.521400
min,21.000000,2014-01-01 00:00:00,0.100000,1.800000e+05,0.000000,300.250000,0.000000,1.842050e+05,1.606620e+05,2014-08-31 00:00:00,0.000000,0.000000
25%,27.000000,2017-04-24 18:00:00,7.200000,5.757158e+05,34637.000000,2500.687500,46101.000000,6.714435e+05,6.122205e+05,2022-05-29 00:00:00,3.000000,16.000000
50%,33.000000,2020-02-27 00:00:00,10.400000,8.533770e+05,77895.000000,4373.455000,76765.500000,1.004886e+06,9.179395e+05,2024-11-25 00:00:00,7.000000,24.000000
75%,38.000000,2023-05-27 00:00:00,13.500000,1.124672e+06,138460.500000,6930.042500,117505.250000,1.335206e+06,1.222124e+06,2026-03-05 00:00:00,12.000000,31.000000
max,62.000000,2026-09-30 00:00:00,20.700000,2.459790e+06,460273.000000,20970.580000,335835.000000,2.819459e+06,2.658552e+06,2026-09-30 00:00:00,31.000000,71.000000
std,7.527762,NaN,4.307403,3.944304e+05,74161.211786,3237.952887,51975.055065,4.741665e+05,4.355951e+05,NaN,6.158704,11.581875